export const techtags=[
    { "label": "JavaScript", "value": "javascript" },
    { "label": "Python", "value": "python" },
    { "label": "Java", "value": "java" },
    { "label": "C#", "value": "c-sharp" },
    { "label": "Ruby", "value": "ruby" },
    { "label": "PHP", "value": "php" },
    { "label": "Node.js", "value": "nodejs" },
    { "label": "React", "value": "react" },
    { "label": "Vue.js", "value": "vuejs" },
    { "label": "Angular", "value": "angular" },
    { "label": "Svelte", "value": "svelte" },
    { "label": "Next.js", "value": "nextjs" },
    { "label": "Nuxt.js", "value": "nuxtjs" },
    { "label": "Express.js", "value": "expressjs" },
    { "label": "Django", "value": "django" },
    { "label": "Flask", "value": "flask" },
    { "label": "Spring Boot", "value": "spring-boot" },
    { "label": "ASP.NET", "value": "asp-net" },
    { "label": "Laravel", "value": "laravel" },
    { "label": "GraphQL", "value": "graphql" },
    { "label": "REST API", "value": "rest-api" },
    { "label": "Microservices", "value": "microservices" },
    { "label": "Docker", "value": "docker" },
    { "label": "Kubernetes", "value": "kubernetes" },
    { "label": "CI/CD", "value": "ci-cd" },
    { "label": "DevOps", "value": "devops" },
    { "label": "AWS", "value": "aws" },
    { "label": "Azure", "value": "azure" },
    { "label": "Google Cloud", "value": "google-cloud" },
    { "label": "Serverless", "value": "serverless" },
    { "label": "Terraform", "value": "terraform" },
    { "label": "Ansible", "value": "ansible" },
    { "label": "Machine Learning", "value": "machine-learning" },
    { "label": "Artificial Intelligence", "value": "artificial-intelligence" },
    { "label": "Deep Learning", "value": "deep-learning" },
    { "label": "Data Science", "value": "data-science" },
    { "label": "NLP", "value": "nlp" },
    { "label": "TensorFlow", "value": "tensorflow" },
    { "label": "PyTorch", "value": "pytorch" },
    { "label": "Pandas", "value": "pandas" },
    { "label": "NumPy", "value": "numpy" },
    { "label": "Scikit-learn", "value": "scikit-learn" },
    { "label": "Big Data", "value": "big-data" },
    { "label": "Hadoop", "value": "hadoop" },
    { "label": "Spark", "value": "spark" },
    { "label": "MongoDB", "value": "mongodb" },
    { "label": "MySQL", "value": "mysql" },
    { "label": "PostgreSQL", "value": "postgresql" },
    { "label": "SQL", "value": "sql" },
    { "label": "NoSQL", "value": "nosql" },
    { "label": "Graph Databases", "value": "graph-databases" },
    { "label": "Blockchain", "value": "blockchain" },
    { "label": "Cryptocurrency", "value": "cryptocurrency" },
    { "label": "Ethereum", "value": "ethereum" },
    { "label": "Solidity", "value": "solidity" },
    { "label": "Web3", "value": "web3" },
    { "label": "Smart Contracts", "value": "smart-contracts" },
    { "label": "Cybersecurity", "value": "cybersecurity" },
    { "label": "Penetration Testing", "value": "penetration-testing" },
    { "label": "Ethical Hacking", "value": "ethical-hacking" },
    { "label": "Encryption", "value": "encryption" },
    { "label": "OAuth", "value": "oauth" },
    { "label": "JWT", "value": "jwt" },
    { "label": "Authentication", "value": "authentication" },
    { "label": "Authorization", "value": "authorization" },
    { "label": "Frontend", "value": "frontend" },
    { "label": "Backend", "value": "backend" },
    { "label": "Full Stack", "value": "full-stack" },
    { "label": "Web Development", "value": "web-development" },
    { "label": "Mobile Development", "value": "mobile-development" },
    { "label": "Android", "value": "android" },
    { "label": "iOS", "value": "ios" },
    { "label": "Flutter", "value": "flutter" },
    { "label": "React Native", "value": "react-native" },
    { "label": "Swift", "value": "swift" },
    { "label": "Kotlin", "value": "kotlin" },
    { "label": "Agile", "value": "agile" },
    { "label": "Scrum", "value": "scrum" },
    { "label": "Kanban", "value": "kanban" },
    { "label": "TDD", "value": "tdd" },
    { "label": "BDD", "value": "bdd" },
    { "label": "Unit Testing", "value": "unit-testing" },
    { "label": "Integration Testing", "value": "integration-testing" },
    { "label": "End-to-End Testing", "value": "end-to-end-testing" },
    { "label": "Selenium", "value": "selenium" },
    { "label": "Jest", "value": "jest" },
    { "label": "Mocha", "value": "mocha" },
    { "label": "Chai", "value": "chai" },
    { "label": "Jenkins", "value": "jenkins" },
    { "label": "Git", "value": "git" },
    { "label": "GitHub", "value": "github" },
    { "label": "GitLab", "value": "gitlab" },
    { "label": "Bitbucket", "value": "bitbucket" },
    { "label": "Version Control", "value": "version-control" },
    { "label": "Linux", "value": "linux" },
    { "label": "Windows", "value": "windows" },
    { "label": "macOS", "value": "macos" },
    { "label": "Command Line", "value": "command-line" },
    { "label": "Shell Scripting", "value": "shell-scripting" },
    { "label": "Cloud Computing", "value": "cloud-computing" },
    { "label": "IoT", "value": "iot" },
    { "label": "AR/VR", "value": "ar-vr" },
    { "label": "Game Development", "value": "game-development" },
    { "label": "Unity", "value": "unity" },
    { "label": "Unreal Engine", "value": "unreal-engine" }
]
