// techCategories.js
export const techCategories = [
    { value: 'Web Development', label: 'Web Development' },
    { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Cloud Computing', label: 'Cloud Computing' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'Mobile App Development', label: 'Mobile App Development' },
    { value: 'Game Development', label: 'Game Development' },
    { value: 'AR/VR', label: 'AR/VR' },
    { value: 'Machine Learning', label: 'Machine Learning' },
    { value: 'Internet of Things (IoT)', label: 'Internet of Things (IoT)' },
    { value: 'Quantum Computing', label: 'Quantum Computing' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'Big Data', label: 'Big Data' },
    { value: 'Edge Computing', label: 'Edge Computing' },
    { value: 'Computer Vision', label: 'Computer Vision' },
    { value: 'Natural Language Processing (NLP)', label: 'Natural Language Processing (NLP)' },
    { value: 'Augmented Reality', label: 'Augmented Reality' },
    { value: 'Virtual Reality', label: 'Virtual Reality' },
    { value: '3D Printing', label: '3D Printing' },
    { value: 'Self-Driving Cars', label: 'Self-Driving Cars' },
    { value: 'Wearable Technology', label: 'Wearable Technology' },
    { value: 'Autonomous Systems', label: 'Autonomous Systems' },
    { value: 'Smart Cities', label: 'Smart Cities' },
    { value: 'Bioinformatics', label: 'Bioinformatics' },
    { value: 'E-Commerce', label: 'E-Commerce' },
    { value: 'FinTech', label: 'FinTech' }, 
    { value: 'InsurTech', label: 'InsurTech' },
    { value: 'HealthTech', label: 'HealthTech' }, 
    { value: 'EdTech', label: 'EdTech' }, 
    { value: 'LegalTech', label: 'LegalTech' }, 
    { value: 'AgriTech', label: 'AgriTech' },
    { value: 'SpaceTech', label: 'SpaceTech' }, 
    { value: 'CleanTech', label: 'CleanTech' }, 
    { value: 'Green Energy', label: 'Green Energy' },
    { value: 'Nanotechnology', label: 'Nanotechnology' },
    { value: 'Digital Twins', label: 'Digital Twins' },
    { value: 'High-Performance Computing (HPC)', label: 'High-Performance Computing (HPC)' },
    { value: 'Serverless Architecture', label: 'Serverless Architecture' },
    { value: 'Containers', label: 'Containers' },
    { value: 'Microservices', label: 'Microservices' },
    { value: 'API Development', label: 'API Development' },
    { value: 'UX/UI Design', label: 'UX/UI Design' },
    { value: 'Automation', label: 'Automation' },
    { value: 'Artificial General Intelligence (AGI)', label: 'Artificial General Intelligence (AGI)' },
    { value: 'No-Code Development', label: 'No-Code Development' },
    { value: 'Low-Code Development', label: 'Low-Code Development' },
    { value: 'Chatbots', label: 'Chatbots' },
    { value: '5G Technology', label: '5G Technology' },
    { value: 'Data Privacy', label: 'Data Privacy' },
    { value: 'Digital Marketing', label: 'Digital Marketing' },
    { value: 'Social Media Technology', label: 'Social Media Technology' },
    { value: 'Quantum Cryptography', label: 'Quantum Cryptography' },
    { value: 'Distributed Systems', label: 'Distributed Systems' },
    { value: 'Functional Programming', label: 'Functional Programming' },
    { value: 'Multithreading', label: 'Multithreading' },
    { value: 'Database Management', label: 'Database Management' },
    { value: 'Search Engine Optimization (SEO)', label: 'Search Engine Optimization (SEO)' },
    { value: 'Digital Transformation', label: 'Digital Transformation' },
    { value: 'IT Infrastructure', label: 'IT Infrastructure' },
    { value: 'Smart Home Technology', label: 'Smart Home Technology' },
    { value: 'Human-Computer Interaction (HCI)', label: 'Human-Computer Interaction (HCI)' },
    { value: 'Open Source', label: 'Open Source' },
    { value: 'Software Engineering', label: 'Software Engineering' },
    { value: 'Cloud Security', label: 'Cloud Security' },
    { value: 'SaaS (Software as a Service)', label: 'SaaS (Software as a Service)' },
    { value: 'PaaS (Platform as a Service)', label: 'PaaS (Platform as a Service)' },
    { value: 'IaaS (Infrastructure as a Service)', label: 'IaaS (Infrastructure as a Service)' },
    { value: 'Server Administration', label: 'Server Administration' },
    { value: 'Digital Payments', label: 'Digital Payments' },
    { value: 'Data Warehousing', label: 'Data Warehousing' },
    { value: 'DevSecOps', label: 'DevSecOps' },
    { value: 'Cyber-Physical Systems', label: 'Cyber-Physical Systems' },
    { value: 'Hybrid Cloud', label: 'Hybrid Cloud' },
    { value: 'API Security', label: 'API Security' },
    { value: 'Data Analytics', label: 'Data Analytics' },
    { value: 'Business Intelligence', label: 'Business Intelligence' },
    { value: 'Content Management Systems (CMS)', label: 'Content Management Systems (CMS)' },
    { value: 'Enterprise Resource Planning (ERP)', label: 'Enterprise Resource Planning (ERP)' },
    { value: 'Customer Relationship Management (CRM)', label: 'Customer Relationship Management (CRM)' },
    { value: 'Software Testing', label: 'Software Testing' },
    { value: 'Agile Methodology', label: 'Agile Methodology' },
    { value: 'SCRUM', label: 'SCRUM' },
    { value: 'Product Management', label: 'Product Management' },
    { value: 'Network Engineering', label: 'Network Engineering' },
    { value: 'AI Ethics', label: 'AI Ethics' },
    { value: 'Tech Policy', label: 'Tech Policy' },
    { value: 'RegTech', label: 'RegTech' }, 
    { value: 'MarTech', label: 'MarTech' }, 
    { value: 'PropTech', label: 'PropTech' }, 
    { value: 'LegalTech', label: 'LegalTech' },
  ];
  