import type { Metadata } from "next";

import "./globals.css";
import Navbar from "../../components/Navbar"
import {Providers} from './provider'




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        <Providers>
        <div className="bg-slate-800 ">
        <Navbar/>
        </div>
       
       

     
        {children}
        
        </Providers>
      </body>
    </html>
  );
}
